site:
  title: SUSE Security Admission Controller
  start_page: 1.31@admission-controller:en:introduction.adoc

content:
  sources:
    - url: ./
      branches: [HEAD]
      start_paths: [shared, dsc-docs/version-*, sboms-docs/v*]

ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ../../../doc-suse-com/dsc-style-bundle/supplemental-files/rancher

asciidoc:
  attributes:
    page-draft-preview-only: 'You can have anything here, just not empty - so this is true, if empty string, or absent, then - false'
    page-pagination: ""
    tabs-sync-option: ""
  extensions:
    - "@asciidoctor/tabs"

antora:
  extensions:
    # - require: "@antora/pdf-extension"
    - require: "@antora/lunr-extension"
      index_latest_only: true
    - require: "@sntke/antora-mermaid-extension"
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
      script_stem: header-scripts # <3>
      mermaid_initialize_options: # <4>
    - require: ../../../product-docs/product-docs-common/extensions/dynamic-loading-attributes/load-global-site-attributes.js
      attributefile: ../../../product-docs/product-docs-common/global-attributes.yml
      enabled: true
    - require: ../../../product-docs/product-docs-common/extensions/versions-latest-prerelease/vlp.js
      enabled: true

output:
  dir: build-local-dsc/site
