---
site:
  title: Kubewarden
  start_page: 1.31@ROOT:ROOT:introduction.adoc

content:
  sources:
    - url: ./
      branches: HEAD
      start_paths: [shared, community-docs/version-*, sboms-docs/v*]

ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./kw-community-docs-supp-files

asciidoc:
  attributes:
    kw-build-community: true
    # build-environment: netlify
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
    - '@asciidoctor/tabs'

antora:
  extensions:
    # - require: "@antora/pdf-extension"
    - require: "@antora/lunr-extension"
      index_latest_only: true
    - require: "@sntke/antora-mermaid-extension"
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
      script_stem: header-scripts
      mermaid_initialize_options:
    - require: ../../../product-docs/product-docs-common/extensions/versions-latest-prerelease/vlp.js
      enabled: true


output:
  dir: build-local-community/site
